{% set name = "django-nose" %}
{% set version = "1.4.6" %}
{% set sha256 = "58934a06a6932696e54c9e8af3fab49bf67ca9e9c840ad668cb7f51219808a07" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - django >=1.8
    - nose >=1.2.1

test:
  imports:
    - django_nose
    - django_nose.management
    - django_nose.management.commands

about:
  home: http://github.com/django-nose/django-nose
  license: BSD 3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: 'Makes your Django tests simple and snappy'

  dev_url: http://github.com/django-nose/django-nose
  doc_url: https://django-nose.readthedocs.io/

extra:
  recipe-maintainers:
    - sodre
