# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "I78WiKy1v5v6bz8lkRK0Zzh51hNv25pxEjkfgiJiLGntZC39EvG6OxUDEHvHuPDWim3eOdJhSdFLf0MjaJzf/o1VFkOOosPbSu9MAV/iQ0rRNfMW/95ha6umozpI3t43JleV0y164XnrmhuMWTsCD+P+GYMjL+TN9lqHkbjZ57TFP+OhsucJRD2e46bUfP2cGn0Ob7XGmI7bDreUpVYjrrXrZHigcL87rpn3zy5rETIx24xsyyT6UDDJRAzX7mIwlYPLia4OaizR9uUWfABAb3G/4whxBgDzTzHb6LjtrB2LxESzyibhjTipCmvOSq+1CZaKkrQEs7wdmedM8x5H00veTXba7Eq5bul+Znn7o2PGUkflNEJUaTVaKKr1/EdwRaEx0BKUunHTab3N/6ppEH8EpdQHvHo2d49xsuCnBPaqBHmFDPBvB4RE4wBskqNbqZFVU6JM3bolbHaFeWhyAcLIj3hFQ0Zmpgcm2D2TeSA2dEmCVMLh0Dys4tgHXTF55QjLK5t8LY+lXgv76pVfcn9JllUxGe5G2qYfM1p8F/B5+pvyonc2QeODwdB+9n8ov+adKhJiA4abljEWte/9wMUOyTHgAP0B1CHOcWqFA5VMc5PQFhyvIwE0jKAuM7G4p+95xKP4826Xh+hUt7azMseQJu9MMWAmWgZexd0u3QQ="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
