travis:
  secure:
    BINSTAR_TOKEN: I78WiKy1v5v6bz8lkRK0Zzh51hNv25pxEjkfgiJiLGntZC39EvG6OxUDEHvHuPDWim3eOdJhSdFLf0MjaJzf/o1VFkOOosPbSu9MAV/iQ0rRNfMW/95ha6umozpI3t43JleV0y164XnrmhuMWTsCD+P+GYMjL+TN9lqHkbjZ57TFP+OhsucJRD2e46bUfP2cGn0Ob7XGmI7bDreUpVYjrrXrZHigcL87rpn3zy5rETIx24xsyyT6UDDJRAzX7mIwlYPLia4OaizR9uUWfABAb3G/4whxBgDzTzHb6LjtrB2LxESzyibhjTipCmvOSq+1CZaKkrQEs7wdmedM8x5H00veTXba7Eq5bul+Znn7o2PGUkflNEJUaTVaKKr1/EdwRaEx0BKUunHTab3N/6ppEH8EpdQHvHo2d49xsuCnBPaqBHmFDPBvB4RE4wBskqNbqZFVU6JM3bolbHaFeWhyAcLIj3hFQ0Zmpgcm2D2TeSA2dEmCVMLh0Dys4tgHXTF55QjLK5t8LY+lXgv76pVfcn9JllUxGe5G2qYfM1p8F/B5+pvyonc2QeODwdB+9n8ov+adKhJiA4abljEWte/9wMUOyTHgAP0B1CHOcWqFA5VMc5PQFhyvIwE0jKAuM7G4p+95xKP4826Xh+hUt7azMseQJu9MMWAmWgZexd0u3QQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
