travis:
  secure:
    BINSTAR_TOKEN: C9XJihGkX1E88kokcf0LTrJ6B3PStk+lN3uXCfNY1x7QJkWnKuOFhE0FveSW18IldB6oYIvoPIg1sliN9QVy3jsQBmQkNwsilFqQH32nYEOW6BUA6ASQ9A1SfwW76mPmfQN8gLmDLobQk49z53N4R3bCwkBgZ2q31ml7MWjKTwNX/RVBL33QKYPgucADHwncFgbetO2JdOi+V60aqc7P2lbZnRo1of5rXpFPECGHkj0KYhFwOHeTmyMShX9QuHGtlzCE+57rdysqmZ0uRrI51J0ByxJn0SoJ/7dPTOot9YqyMcM+WX8i+5v8cFsF7rU4tnBiDQ7Vv2/esKX+uzBcHcspNJ8impWFoDw5YwHvDNPe9poZDv0K7ZlL07iMVFxuK0WwBfVWKajLgt+y9RghkfTFqtOMYKSwkR7WJXusuoTcNqz3/oU8+/qK/89ldJKh74pmOZqXv855jWhLSaqintgA18jdv6yAYsK+E6fiwTguzys7os6Le8X0AJPIEnR3vzxgqKxolm31hSGQcG93NdRzXkbDvjO9rgjk2q905FndogOiIOgKtpDh+SnEreWPCr96XFiVaeVAnnyw56KpBypiLOGheB33pbiIuVm43N1eEl2fP5AfP6Vfkr8EveUzYblQnDrQvQmlth/73MxW/JImdpoB0Jp+dPRgxPWuavo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
