travis:
  secure:
    BINSTAR_TOKEN: nq0qYqcuEj7BDq5/t7QMXc727lzVbf2YuMGcyIP3PWh+wgfd/wzV/GNi2Atqs3ShW5NSPv9S8UG5dQJP2E2wkVlwlKfiOfMg3ZUjEGSio7j64IZHLypBGNl75uQA3Q7PIknD9zRpP9WxodKF3ft3RqVgMWDYl+OJ9fbF5C5FTh3sN2YfDfMGV16A4doUNZv+ZqmAJTvK31SweKa043Aivk4CyFcQafuP1Kz3PIa+zREKz1E2JEIyeQhkNgNxFzSc2PAGUUHKy9ld1fR0Vl4vCYrkwhy4x3ezzXN0E3XEBakZdXMKIPRw2FsT4deDTvtpIcF1bm4IF72ALg9AnAxpyE7J9Z3+sQ+l4LgG3QVY+qKLW3xcV2N44IcCQawCG3J2LY23Oiy2pfNxUQZ8gtpLvyaVPhHHC6gf7mc+ZxgrROpFV+RoZKdmYrpyZpWiSKLZOlhQEFyt3lRqA+ecKhD6tOYc0RnG9Ufx7Tu4T3PW4wfD+fTgDUTSpbXuSze9U62PNbw63U1ewCJwypLP9PyHapevWIvUGxS/U7mz/1ZExQoxcLJJZMuv/qpT7ypE+eGnyD+UugK63HR2d+Japiig/F7pmasdUQrFRElxW/a/U7wHAqAntecMt99B42GN1063E1wDbeYw2b3QiwySJ3JROLzvaDUsrobb7itvHUNIkXw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
